name: Build macOS

on:
  push:
    branches: [main, macos]
  pull_request:
    branches: [main, macos]

jobs:
  build-intel:
    runs-on: macos-13  # Intel
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        run: bash build-scripts/setup-dev.sh

      - name: Configure CMake
        run: cmake --preset macos-x64

      - name: Build
        run: cmake --build --preset macos-x64 --config ${{ matrix.config }}

      - name: Upload Artifact
        if: matrix.config == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: toss-pos-macos-x64-${{ matrix.config }}
          path: build/macos-x64/${{ matrix.config }}/toss-pos
          retention-days: 30

  build-arm64:
    runs-on: macos-14  # Apple Silicon
    strategy:
      matrix:
        config: [Release, Debug]

    steps:
      - uses: actions/checkout@v4

      - name: Setup vcpkg
        run: bash build-scripts/setup-dev.sh

      - name: Configure CMake
        run: cmake --preset macos-arm64

      - name: Build
        run: cmake --build --preset macos-arm64 --config ${{ matrix.config }}

      - name: Upload Artifact
        if: matrix.config == 'Release'
        uses: actions/upload-artifact@v3
        with:
          name: toss-pos-macos-arm64-${{ matrix.config }}
          path: build/macos-arm64/${{ matrix.config }}/toss-pos
          retention-days: 30
